# Generated by Django 3.2.7 on 2021-09-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20210908_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at',)},
        ),
    ]
